name: Detect docker base image updates

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:


jobs:

  check-update:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # for Keepalive
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Keep repo alive: https://github.com/marketplace/actions/keepalive-workflow
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v2

      - name: Get Image Names
        id: images
        run: |
          echo "IMAGE_BASE=$(grep "^FROM" Dockerfile | head -n 1 | sed 's/^FROM\s\+//')" | tee -a $GITHUB_ENV
          echo "IMAGE_DERIVED=ghcr.io/${GITHUB_REPOSITORY}:master" | tee -a $GITHUB_ENV

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: ${{ env.IMAGE_BASE }}
          image: ${{ env.IMAGE_DERIVED }}

      # Debug step to see the output
      - name: Debug Output
        run: |
          echo "Differs output: ${{ steps.check.outputs.needs-updating }}"

  call-build:
    needs: check-update
    if: needs.check-update.outputs.needs-updating == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-docker-image.yml
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write